DROP USER PRJ2531B CASCADE;
CREATE USER PRJ2531B IDENTIFIED BY PRJ2531B;
GRANT CONNECT, RESOURCE TO PRJ2531B;
GRANT DBA TO PRJ2531B;
CONN PRJ2531B/PRJ2531B;

CREATE TABLE PRODUCT(
PR_ID   VARCHAR2(10) PRIMARY KEY,
PR_NM   VARCHAR2(20) NOT NULL,
CTG     VARCHAR2(20) NOT NULL,
BR_NM   VARCHAR2(20) NOT NULL,
PRICE   NUMBER(8,2)  NOT NULL,
WT      VARCHAR2(20) NOT NULL,
UNIT    VARCHAR2(10) NOT NULL,
TYPE    VARCHAR2(20) NOT NULL);

CREATE TABLE SUP_DET(
SUP_ID   VARCHAR2(10) PRIMARY KEY,
SUP_PH   NUMBER(10)   NOT NULL,
CON_PER  VARCHAR2(20) NOT NULL,
CON_NO   NUMBER(10)   NOT NULL,
CMP_NM   VARCHAR(20)  NOT NULL,
ADDR     VARCHAR2(100) NOT NULL,
BNK_NM   VARCHAR2(50) NOT NULL,
BR_NM    VARCHAR2(50) NOT NULL,
AC_HLDR  VARCHAR2(20) NOT NULL,
AC_NO    NUMBER(20)   NOT NULL,
IFSC     VARCHAR2(20) NOT NULL,
GST_NO   VARCHAR2(15) NOT NULL);

CREATE TABLE CUSTOMER(
CUST_ID VARCHAR(10) PRIMARY KEY,
CUST_NM VARCHAR2(50) NOT NULL,
PHNO    VARCHAR2(10) NOT NULL,
ADDR    VARCHAR2(255) NOT NULL);

CREATE TABLE EMPLOYEE(
EMP_ID VARCHAR2(10) PRIMARY KEY,
EMP_NM VARCHAR2(20) NOT NULL,
ROLE   VARCHAR2(50) NOT NULL,
PHNO   NUMBER(10) NOT NULL,
H_DT   DATE       NOT NULL,
SAL    NUMBER(8,2) CHECK(SAL BETWEEN 10000.00 AND 50000.00),
EXP    VARCHAR2(20) CHECK(EXP>=0),
QAL    VARCHAR2(30) NOT NULL);

CREATE TABLE QUOTATION(
Q_ID       VARCHAR2(10) PRIMARY KEY,
Q_DATE     DATE         NOT NULL,
VALID_UPTO DATE         NOT NULL,
SUP_ID     VARCHAR2(10) REFERENCES SUP_DET(SUP_ID));


CREATE TABLE Q_PROD_DET(
Q_ID VARCHAR2(10) REFERENCES QUOTATION(Q_ID),
PR_ID VARCHAR2(10) REFERENCES PRODUCT(PR_ID),
PACK VARCHAR(20) NOT NULL,
RATE NUMBER(7,2) NOT NULL);


CREATE TABLE STOCK(
PR_ID  VARCHAR2(10) REFERENCES PRODUCT(PR_ID),
CURRENT_QTY   NUMBER(10) NOT NULL,
LAST_UPDATE DATE NOT NULL);

CREATE TABLE ORDER_MASTER(
ORD_ID VARCHAR2(10) PRIMARY KEY,
ORD_DATE DATE NOT NULL,
DEL_DATE DATE NOT NULL,
SUP_ID VARCHAR2(10) REFERENCES SUP_DET(SUP_ID),
NET_AMOUNT NUMBER(8,2) NOT NULL,
CURR_ADV NUMBER(8,2) NOT NULL,
DUES NUMBER(8,2) NOT NULL,
PAY_MODE VARCHAR2(10) NOT NULL,
STATUS VARCHAR2(20) NOT NULL);


CREATE TABLE ORDER_DETAILS(
ORD_ID   VARCHAR2(10) REFERENCES ORDER_MASTER(ORD_ID),
PR_ID    VARCHAR2(10) REFERENCES PRODUCT(PR_ID),
PRICE    NUMBER(8,2)  NOT NULL,
QTY      NUMBER(10)   NOT NULL,
GST      NUMBER(5,2) NOT NULL CHECK(GST>=0),
TOTAL    NUMBER(8,2) NOT NULL);


CREATE TABLE SALE_MASTER(
SALE_ID VARCHAR2(10) PRIMARY KEY,
SALE_DATE DATE NOT NULL,
CUST_ID VARCHAR2(10) REFERENCES CUSTOMER(CUST_ID),
NET_AMOUNT NUMBER(8,2) NOT NULL,
ADVANCE NUMBER(8,2) NOT NULL,
DUES NUMBER(8,2) NOT NULL,
PAY_MODE VARCHAR2(10) NOT NULL);

CREATE TABLE SALE_DETAILS(
SALE_ID VARCHAR2(10) REFERENCES SALE_MASTER(SALE_ID),
PR_ID   VARCHAR2(10) REFERENCES PRODUCT(PR_ID),
PRICE  NUMBER(8,2) NOT NULL,
QTY  NUMBER(10) NOT NULL,
GST NUMBER(5,2) NOT NULL CHECK(GST>=0),
TOTAL NUMBER(8,2) NOT NULL);

                         

